# -*- coding: utf-8 -*-
"""resume_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oY65hIGOMZCIufvdgsYml85UbRwlaGoi
"""

import re

# simple list of technical skills
skills = [
    "python",
    "machine learning",
    "deep learning",
    "data analysis",
    "sql",
    "pandas",
    "numpy",
    "pytorch",
    "tensorflow"
]

def extract_skills(text):
    text = text.lower()
    found = []

    for skill in skills:
        if re.search(r"\b" + re.escape(skill) + r"\b", text):
            found.append(skill)

    return found


if __name__ == "__main__":

    with open("sample_cv.txt", "r") as f:
        resume = f.read()

    detected = extract_skills(resume)

    print("Detected skills:")
    for s in detected:
        print("-", s)